CREATE TABLE map (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`latitude` VARCHAR(50) NULL DEFAULT NULL,
	`longitude` VARCHAR(50) NULL DEFAULT NULL,
	`title` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`address` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`comment` VARCHAR(2000) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`display_flag` CHAR(1) NOT NULL DEFAULT 'N' COLLATE 'utf8_general_ci',
	`reg_id` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`reg_date` DATETIME NULL DEFAULT NULL,
	`mod_id` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`mod_date` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;